spring:
  main:
    log-startup-info: true
  application:
    name: product-service
  mvc:
    problemdetails:
      enabled: true

spring.datasource:
  url: jdbc:h2:mem:products;DB_CLOSE_DELAY=-1;
  username: sa
  password:

spring.jdbc:
  template:
    batch-size: 1000
    fetch-size: 1000

spring.sql:
  init:
    schema-locations: classpath:h2/schema.sql

server:
  address: localhost
  port: 9010
  servlet:
    context-path: /web-store/products/v1/api
    
logging:
  level:
    root: INFO
    mike.spring.webstore: DEBUG
    org.springframework: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: list
