CREATE TABLE T_PRODUCT(
  ID       INT            NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME     VARCHAR(50)    NOT NULL,
  PRICE    NUMERIC(10, 2) NOT NULL,
  QUANTITY INT            NOT NULL
);

INSERT INTO T_PRODUCT(name, price, quantity) VALUES ('PRODUCT-1', 10.25, 100);

COMMIT;